### ISSUE TITLE
Code compatible with terraform 0.13?

### ISSUE THREAD

**Issue by burvilc** [ned1313/Getting-Started-Terraform#12]
I got this when I try to run 'terraform init'.  Is this code tested to work with 0.13?  I tried running the command suggested, and run into problems, seemingly because the alternative provider isn't valid anymore.  

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/azurerm v1.44.0
- Using previously-installed hashicorp/random v3.0.0
- Using previously-installed hashicorp/aws v3.15.0
- Finding latest version of hashicorp/azure...

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/azure -> terraform-providers/azure

If these suggestions look correct, upgrade your configuration with the
following command:
    terraform 0.13upgrade .

```

It seems there are significant changes in 0.13, and I don't think it makes sense to use an old version anyway.

**Comment by ned1313** [comment]
I've updated the the configurations to use version ~2.0 of the Azure RM provider and added the new style `required_providers` block to set the version of the provider.
