### ISSUE TITLE
m5.tfplan S3 bucket /nginx/ folder creation issue

### ISSUE THREAD

**Issue by vlatkojordanov90** [ned1313/Getting-Started-Terraform#14]
Hi,

Not sure what happened but I tried manual execution of this
`/usr/local/bin/s3cmd sync --config=/home/ec2-user/.s3cfg /var/log/nginx/ s3://globo-dev-59843/nginx/i-06e34b5321f02686b/`

(don't worry this is a sandbox so everything above will be irrelevant in couple of mins)

and this executed as expected:
`i-06e34b5321f02686b[root@ip-10-1-0-231 ec2-user]#
[root@ip-10-1-0-231 ec2-user]# /usr/local/bin/s3cmd sync --config=/home/ec2-user/.s3cfg /var/log/nginx/ s3://globo-dev-59843/nginx/i-06e34b5321f02686b/
upload: '/var/log/nginx/access.log' -> 's3://globo-dev-59843/nginx/i-06e34b5321f02686b/access.log'  [1 of 3]
 0 of 0     0% in    0s     0.00 B/s  done
upload: '/var/log/nginx/access.log-20210531.gz' -> 's3://globo-dev-59843/nginx/i-06e34b5321f02686b/access.log-20210531.gz'  [2 of 3]
 20 of 20   100% in    0s   707.16 B/s  done
upload: '/var/log/nginx/error.log' -> 's3://globo-dev-59843/nginx/i-06e34b5321f02686b/error.log'  [3 of 3]
 0 of 0     0% in    0s     0.00 B/s  done
remote copy: 'access.log-20210531.gz' -> 'error.log-20210531.gz'
Done. Uploaded 20 bytes in 1.0 seconds, 20.00 B/s.`

However when I applied this via tf apply m5.tfplan it skipped this part???:

`  provisioner "file" {
    content = <<EOF
/var/log/nginx/*log {
    daily
    rotate 10
    missingok
    compress
    sharedscripts
    postrotate
    endscript
    lastaction
        INSTANCE_ID=`curl --silent http://169.254.169.254/latest/meta-data/instance-id`
        sudo /usr/local/bin/s3cmd sync --config=/home/ec2-user/.s3cfg /var/log/nginx/ s3://${aws_s3_bucket.web_bucket.id}/nginx/$INSTANCE_ID/
    endscript
}`

It's like the "file" provisioner was skipped, which was not the case with the "remote-exec" one and the /website/ was created. What would happen if this action is moved to the "remote-exec" provisioner? Haven't tried it yet, wondering if that might fix anything? 

Cheers,
Vlatko

**Comment by Codex1024** [comment]
I believe I am also seeing issues with the nginx
The instances, S3 bucket and other are all created. I can browse to the Globomantics test site.
Applying the Terraform plan is reporting an error during Remote-execution. I observe no ngnix folder in the S3 bucket.
I don't think I missed any steps of the tutorial.

_aws_instance.nginx1 (remote-exec): error: nginx:1 lines must begin with a keyword or a filename (possibly in double quotes)
aws_instance.nginx1 (remote-exec): error: nginx:2 unexpected text
aws_instance.nginx1 (remote-exec): error: nginx:3 unexpected text
aws_instance.nginx1 (remote-exec): error: nginx:4 unexpected text
aws_instance.nginx1 (remote-exec): error: nginx:5 unexpected text
aws_instance.nginx1 (remote-exec): error: nginx:6 unexpected text
aws_instance.nginx1 (remote-exec): error: nginx:prerotate or postrotate without endscript
aws_instance.nginx1 (remote-exec): error: found error in file nginx, skipping_
