### ISSUE TITLE
M3: No default VPC found in this region

### ISSUE THREAD

**Issue by wely** [ned1313/Getting-Started-Terraform#15]
Module 3:
When performing **terraform apply "m3.tfplan"**  

│ Error: No default VPC found in this region.
│
│   with aws_default_vpc.default,
│   on module_three.tf line 53, in resource "aws_default_vpc" "default":
│   53: resource "aws_default_vpc" "default" {

Though i have confirmed that there's a default VPC in my region.
![image](https://user-images.githubusercontent.com/1658657/130714397-286918e8-927e-42a5-904c-15009e401af1.png)

The current context in AWS CLI has also been set to the respective region.

![image](https://user-images.githubusercontent.com/1658657/130714484-251fba86-c7c7-488d-9112-1f416f955d38.png)

**Comment by ned1313** [comment]
That's correct. There's also a newer version of this course that doesn't use the default VPC to avoid this issue.
