### ISSUE TITLE
Question on the code

### ISSUE THREAD

**Issue by itinneed** [ned1313/Getting-Started-Terraform#16]
I'm sorry to use Github as a Q&A but Pluralsight's Disqus is broken.

In each modules .tf files you have a data source:
data "aws_availability_zones" "available" {}

and then in the resources you have defined:

data.aws_availability_zones.available.names[0]
and
data.aws_availability_zones.available.names[1]

Where is this list, names, being populated?

**Comment by ned1313** [comment]
The data source aws_availability_zones.available has attributes associated with it. One of those attributes is the name attribute, which is a list of the names of availability zones. You can find more about the data source in the official docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/availability_zones
