### ISSUE TITLE
M3 folder is not available

### ISSUE THREAD

**Issue by dinjains2003** [ned1313/Getting-Started-Terraform#20]
hi ,

I am new to your Pluralsight course and I can not see M3 folder.
![image](https://user-images.githubusercontent.com/50724391/140174453-626f8708-e4b3-4b13-a41e-f7b4204b0b2c.png)

**Comment by ned1313** [comment]
Hi! A new version of the course has just published with and that is what you will see on the main branch. The older version of the files are available on the pre-1.0 branch.
