### ISSUE TITLE
Hi, where is the m3 folder. I'm trying to follow the course under the plural sight.

### ISSUE THREAD

**Issue by Varmaj** [ned1313/Getting-Started-Terraform#23]

**Comment by tejas-2232** [comment]
Yeah. I have the same question. @Varmaj 

> **@ned1313 can you please have a look.**

**Comment by ned1313** [comment]
I'm guessing you're taking an older version of the course that had a different folder structure. [Check out the pre-1.0 branch](https://github.com/ned1313/Getting-Started-Terraform/tree/pre-1.0) for those files or take the newer version of the course.
