### ISSUE TITLE
Latest AWS provider(version 4) does not work with some arguements in m5 solution

### ISSUE THREAD

**Issue by Abhinand-Gokul** [ned1313/Getting-Started-Terraform#25]
Hello Ned,

I was following along your course and I see that some arguements are deprecated. For example : 

`terraform validate
╷
│ Warning: Argument is deprecated
│ 
│   with aws_s3_bucket.web_bucket,
│   on s3.tf line 57, in resource "aws_s3_bucket" "web_bucket":
│   57:   acl           = "private"
│ 
│ Use the aws_s3_bucket_acl resource instead
│ 
│ (and 5 more similar warnings elsewhere)
╵
Success! The configuration is valid, but there were some validation warnings as shown above.`

I am using : 
`terraform version
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.18.0
+ provider registry.terraform.io/hashicorp/random v3.3.1`

I had to use AWS provider version 4 as I was getting errors while performing validate : 
`terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Finding hashicorp/random versions matching "~> 3.3"...
- Installing hashicorp/random v3.3.1...
- Installed hashicorp/random v3.3.1 (signed by HashiCorp)
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/aws: locked provider registry.terraform.io/hashicorp/aws 4.18.0 does not match configured
│ version constraint ~> 3.0; must use terraform init -upgrade to allow selection of new versions`

Would it be possible to update m5 solutions to incorporate updated arguements?

**Comment by ned1313** [comment]
For the time being, I'd like to stay on the older version of the provider to avoid any other breaking changes. You can always downgrade to major version 3 by running `terraform init -upgrade`. That will update the constraint in the dependency lock file and download the current major version 3 plugin for AWS.
