### ISSUE TITLE
Module 6 instances.tf missing `iam_instance_profile` and `depends_on` for nginx2 instance

### ISSUE THREAD

**Issue by daniel-packard** [ned1313/Getting-Started-Terraform#29]
In `m6_solution/instances.tf` the config for nginx2 is missing some important config values (iam_instance_profile, and depends_on) when compared to nginx1.

nginx1: 
https://github.com/ned1313/Getting-Started-Terraform/blob/c19a68171dc29597ffa398b8eb7aa325fa024872/m6_solution/instances.tf#L14-L20

nginx2:
https://github.com/ned1313/Getting-Started-Terraform/blob/c19a68171dc29597ffa398b8eb7aa325fa024872/m6_solution/instances.tf#L37-L42

This results in one healthy instance (nginx1) and one unhealthy instance (nginx2)

**Comment by ned1313** [comment]
This has been resolved with the newest version of the course.
