### ISSUE TITLE
Provisioning file using terraform in Windows errors on Amazon linux VM

### ISSUE THREAD

**Issue by jacktar283** [ned1313/Getting-Started-Terraform#4]
Within Module 5, the terraform apply deploys an nginx configuration for the logrotate software using here-doc notation (lines ~249-264/317-332). When executed on Windows, the file is deployed as a DOS file and logrotate errors when trying to run. Errors will be seen in the output as shown below when the logrotate command is executed on each instance. (The output below shows the second instance only, but the same occurs for nginx1)

'''
aws_instance.nginx2 (remote-exec): error: nginx:1 lines must begin with a keyword or a filename (possibly in double quotes)
aws_instance.nginx2 (remote-exec): error: nginx:2 unexpected text
aws_instance.nginx2 (remote-exec): error: nginx:3 unexpected text
aws_instance.nginx2 (remote-exec): error: nginx:4 unexpected text
aws_instance.nginx2 (remote-exec): error: nginx:5 unexpected text
aws_instance.nginx2 (remote-exec): error: nginx:6 unexpected text
aws_instance.nginx2 (remote-exec): error: nginx:prerotate or postrotate without endscript
aws_instance.nginx2 (remote-exec): error: found error in file nginx, skipping
'''
Note: Whilst this is problematic, Module 5 serves to demonstrate the use of provisioners and clearly states that they should only be used as a last resort. There are probably better/recommended methods to achieve the end result than demonstrated here.

This is using Terraform v0.12.24 with AWS provider v2.58.0 and the current AMI image "ami-01a6e31ac994bbc09" (AL2 with kernel 4.14, systemd 219, GCC7.3, Glibc2.26, Binutils2.29.1) and logrotate-3.7.8-26.14.amzn1.x86_64)
The errors occur as a result of the CRLF mappings between UNIX & DOS.

Whilst the local solution on the linux VM is simple enough to effect, is there any mechanism that Terraform can provision files using the system native format? i.e. DOS for Windows, unix for Linux VMs,

**Comment by m-j-gardner** [comment]
I had the same problem but a quick fix is to use VS Code and toggle between LF/CRLF endings by clicking on the CRLF letters at the bottom of the window (to change to LF) and saving the file.  Worked for me after that.

**Comment by ned1313** [comment]
I've updated the .tf files to all use LF endings.

**Comment by imran-uk** [comment]
I had this issue on Windows with Sublime Text 3.

By defauly it opens the files from Git with Windows line endings. Even with `"default_line_ending": "unix",` in my settings.

I put this in my settings `"show_line_endings": true` and then saved the tf files, plan/apply and then it worked.
