### ISSUE TITLE
Terraform was not able to find KeyPair

### ISSUE THREAD

**Issue by jamesenki** [ned1313/Getting-Started-Terraform#7]
Taking your course on Pluralsight and trying to do the work along side. Terraform is not able to find the KeyPairs though and that is fairly frustrating 

rror: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'Pluralsight' does not exist
        status code: 400, request id: 2de81fda-4527-4418-8bb4-a5d94d85739c

I have created the key pair in advance in the aws console

**Comment by blkdev02** [comment]
I had the same problem and made some changes have a look 
https://github.com/blkdev02/Introduction_to_Terraform/tree/master/module_3

**Comment by hakalachi** [comment]
I ran into this issue as well, and it turns out that I had the wrong AWS region in line 10 of module[x].tf.  Make sure you update that to match the region your keys are in. Example: default = "us-west-2"

**Comment by ned1313** [comment]
Closing issue
