### ISSUE TITLE
no such file/dir error during remote-exec (m4)

### ISSUE THREAD

**Issue by sleightsec** [ned1313/Getting-Started-Terraform#9]
Get the following output when applying m4 scripts. Appears to be either a change to ami selected and/or change to ami itself. On the ami selected the index.html exists as a symlink to a different file (fedora). Deleting the symlink first resolves the issue. 

the file:
[ec2-user@ip-10-1-0-33 ~]$ ls -al /usr/share/nginx/html/index.html
lrwxrwxrwx 1 root root 32 Sep 18 00:19 /usr/share/nginx/html/index.html -> ../../fedora-testpage/index.html
[ec2-user@ip-10-1-0-33 ~]$ 

terraform apply output:
aws_instance.nginx1 (remote-exec): Dependency Installed:
aws_instance.nginx1 (remote-exec):   gperftools-libs.x86_64 0:2.0-11.5.amzn1
aws_instance.nginx1 (remote-exec):   libunwind.x86_64 0:1.1-10.8.amzn1
 
aws_instance.nginx1 (remote-exec): Complete!
aws_instance.nginx1 (remote-exec): Starting nginx:         [  OK  ]
aws_instance.nginx1 (remote-exec): tee: /usr/share/nginx/html/index.html: No such file or directory
aws_instance.nginx1 (remote-exec): <html><head><title>Blue Team Server</title></head><body style="background-color:#1F778D"><p style="text-align: center;"><span style="color:#FFFFFF;"><span style="font-size:28px;">Blue Team</span></span></p></body></html>

Error: error executing "/tmp/terraform_1667424955.sh": Process exited with status 1

**Comment by ned1313** [comment]
Merged changes, thanks!
